### ISSUE TITLE
still does not compile correctly in linux 

### ISSUE THREAD

**Issue by Malifick** [gratrix/vcv-gratrix#2]
src/Fade02.cpp: In constructor ‘Fade02Bank::Fade02Bank()’:
src/Fade02.cpp:76:21: error: no matching function for call to ‘rack::Module::Module(Fade02::ParamIds, int, int, Fade02::LightIds)’
   Fade02::NUM_LIGHTS)
                     ^
In file included from ../../include/rack.hpp:6:0,
                 from src/Gratrix.hpp:10,
                 from src/Fade02.cpp:1:
../../include/engine.hpp:43:2: note: candidate: rack::Module::Module(int, int, int)
  Module(int numParams, int numInputs, int numOutputs) {
  ^~~~~~
../../include/engine.hpp:43:2: note:   candidate expects 3 arguments, 4 provided
../../include/engine.hpp:41:2: note: candidate: rack::Module::Module()
  Module() {}
  ^~~~~~
../../include/engine.hpp:41:2: note:   candidate expects 0 arguments, 4 provided
../../include/engine.hpp:33:8: note: candidate: rack::Module::Module(const rack::Module&)
 struct Module {
        ^~~~~~
../../include/engine.hpp:33:8: note:   candidate expects 1 argument, 4 provided
src/Fade02.cpp:78:3: error: ‘lights’ was not declared in this scope
   lights[Fade02::IN1AP_LIGHT].value = -1.0f;
   ^~~~~~
src/Fade02.cpp:78:3: note: suggested alternative: ‘glLighti’
   lights[Fade02::IN1AP_LIGHT].value = -1.0f;
   ^~~~~~
   glLighti
src/Fade02.cpp: In member function ‘virtual void Fade02Bank::step()’:
src/Fade02.cpp:115:3: error: ‘lights’ was not declared in this scope
   lights[Fade02::OUT1AP_LIGHT].value = 2.0f * blendAB - 1.0f;
   ^~~~~~
src/Fade02.cpp:115:3: note: suggested alternative: ‘glLighti’
   lights[Fade02::OUT1AP_LIGHT].value = 2.0f * blendAB - 1.0f;
   ^~~~~~
   glLighti
src/Fade02.cpp: In constructor ‘Fade_G2_Widget::Fade_G2_Widget()’:
src/Fade02.cpp:190:13: error: ‘createLight’ was not declared in this scope
    addChild(createLight<SmallLight<GreenRedLight>>(led(gx(x)+rad_led()/2+28, gy(y+1)-46-rad_led()), module, i++));
             ^~~~~~~~~~~
src/Fade02.cpp:190:13: note: suggested alternative: ‘GreenRedLight’
    addChild(createLight<SmallLight<GreenRedLight>>(led(gx(x)+rad_led()/2+28, gy(y+1)-46-rad_led()), module, i++));
             ^~~~~~~~~~~
             GreenRedLight
In file included from src/Fade02.cpp:1:0:
src/Gratrix.hpp:13:23: error: ‘RedLight’ was not declared in this scope
 #define GreenRedLight RedLight
                       ^
src/Fade02.cpp:190:36: note: in expansion of macro ‘GreenRedLight’
    addChild(createLight<SmallLight<GreenRedLight>>(led(gx(x)+rad_led()/2+28, gy(y+1)-46-rad_led()), module, i++));
                                    ^~~~~~~~~~~~~
src/Gratrix.hpp:13:23: note: suggested alternative: ‘glLighti’
 #define GreenRedLight RedLight
                       ^
src/Fade02.cpp:190:36: note: in expansion of macro ‘GreenRedLight’
    addChild(createLight<SmallLight<GreenRedLight>>(led(gx(x)+rad_led()/2+28, gy(y+1)-46-rad_led()), module, i++));
                                    ^~~~~~~~~~~~~
src/Gratrix.hpp:13:23: error: template argument 1 is invalid
 #define GreenRedLight RedLight
                       ^
src/Fade02.cpp:190:36: note: in expansion of macro ‘GreenRedLight’
    addChild(createLight<SmallLight<GreenRedLight>>(led(gx(x)+rad_led()/2+28, gy(y+1)-46-rad_led()), module, i++));
                                    ^~~~~~~~~~~~~
src/Fade02.cpp:190:110: warning: right operand of comma operator has no effect [-Wunused-value]
 GreenRedLight>>(led(gx(x)+rad_led()/2+28, gy(y+1)-46-rad_led()), module, i++));
                                                                           ^~
In file included from src/Fade02.cpp:1:0:
src/Gratrix.hpp:13:23: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
 #define GreenRedLight RedLight
                       ^
src/Fade02.cpp:191:36: note: in expansion of macro ‘GreenRedLight’
    addChild(createLight<SmallLight<GreenRedLight>>(led(gx(x)+rad_led()/2+28, gy(y+1)-46+rad_led()), module, i++));
                                    ^~~~~~~~~~~~~
src/Gratrix.hpp:13:23: note:   expected a type, got ‘RedLight’
 #define GreenRedLight RedLight
                       ^
src/Fade02.cpp:191:36: note: in expansion of macro ‘GreenRedLight’
    addChild(createLight<SmallLight<GreenRedLight>>(led(gx(x)+rad_led()/2+28, gy(y+1)-46+rad_led()), module, i++));
                                    ^~~~~~~~~~~~~
src/Fade02.cpp:191:110: warning: right operand of comma operator has no effect [-Wunused-value]
 GreenRedLight>>(led(gx(x)+rad_led()/2+28, gy(y+1)-46+rad_led()), module, i++));
                                                                           ^~
make: *** [../../compile.mk:55: build/src/Fade02.cpp.o] Error 1

**Comment by gratrix** [comment]
The first error is because I'm using the dev version of rack which has a different api to 0.4. See https://github.com/VCVRack/Rack/issues/258#issuecomment-339675761
