### ISSUE TITLE
What is the reason for updating the name of a module from Env-F1 to ADSR-F1?

### ISSUE THREAD

**Issue by vogelscheiss** [gratrix/vcv-gratrix#7]
The Gratrix envelope module used to be called this:

<img width="189" alt="screen shot 2018-04-09 at 4 21 31 pm" src="https://user-images.githubusercontent.com/38222883/38521017-6e53b794-3c12-11e8-90b6-f54c022f77a5.png">

Now it's called this:

<img width="178" alt="screen shot 2018-04-09 at 4 22 41 pm" src="https://user-images.githubusercontent.com/38222883/38521049-84235912-3c12-11e8-9a4d-76ed1fb37b4e.png">

I don't understand why this was done. It ruined backward compatibility of patches, which now all have to be edited to refer to the new name.

Is there an underlying purpose?

**Comment by vogelscheiss** [comment]
![image](https://user-images.githubusercontent.com/38222883/38590340-89b6703e-3cfe-11e8-9a55-ccc4bbd36dce.png)

**Comment by gratrix** [comment]
I felt that I should keep the name consistent with the Fundamental models.
